# -*- coding: utf-8 -*-
"""xpath_0_測試各站.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UHw0ne2ZojjAr_6-QD7CPxj8jLmtcvF
"""

#安裝相關函式庫
!pip install requests

import requests
import ssl
from urllib3 import poolmanager
from lxml import etree

class TLSAdapter(requests.adapters.HTTPAdapter):

    def init_poolmanager(self, connections, maxsize, block=False):
        """Create and initialize the urllib3 PoolManager."""
        ctx = ssl.create_default_context()
        ctx.set_ciphers('DEFAULT@SECLEVEL=1')
        self.poolmanager = poolmanager.PoolManager(
                num_pools=connections,
                maxsize=maxsize,
                block=block,
                ssl_version=ssl.PROTOCOL_TLS,
                ssl_context=ctx)

#可以從瀏覽器的開發者工具取得 request 的 header 資訊
headers_Get = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36'
    }

#請求網頁
def requestHtml(url):
  s = requests.Session()
  #s.mount('https://', TLSAdapter())
  r = s.get(url, headers=headers_Get)
  #r = s.get(url)
  #r.encoding = r.apparent_encoding
  #print(r.text)
  return etree.HTML(r.text)

url = 'https://news.ltn.com.tw/list/breakingnews/world'
dom = requestHtml(url)

#取得父(祖)層屬性的3種寫法
links = dom.xpath('//a[.//h3[@class="title"]]/@href')
#links = dom.xpath('//h3[@class="title"]/parent::*/parent::a[@class="tit"]/@href')
#links = dom.xpath('//h3[@class="title"]/ancestor::a[@class="tit"]/@href')
titles = dom.xpath('//h3[@class="title"]/text()')
print(links)
print(titles)

#博客來
url = 'https://www.books.com.tw/web/sys_bbotm/books/190102/'
dom = requestHtml(url)

links = dom.xpath('//h4/a/@href')
titles = dom.xpath('//h4/a/text()')
print(links)
print(titles)

#疑似該站的 robots.txt 描述裡禁止爬蟲，如果 header 資訊都用上了仍沒用，就只能用 Selenium 
#見 https://www.mobile01.com/robots.txt

url = 'https://www.mobile01.com/marketcommoditylist.php?f=383'
dom = requestHtml(url)

titles = dom.xpath('//div[@class="l-articleCardDesc"]/text()')

print(titles)

#要注意該站的 request header 的資訊要正確

url = 'https://icook.tw/categories/28'
dom = requestHtml(url)

titles = dom.xpath('//h2[@class="browse-recipe-name"]/text()')

print(titles)

#田邊好幫手的網站機制造成無法取得列表，只能用 Selenium

url = 'https://m.coa.gov.tw/News/Index?Category=2'
dom = requestHtml(url)

links = dom.xpath('//td/a[@class="btn-detail"]/@href')
titles = dom.xpath('//td/a[@class="btn-detail"]/text()')

print(links)
print(titles)

#Google 新聞取得的網址是中繼網址，連到各站的新聞內頁時，內容格式各站皆不同，接下來將導致無法正確爬取內容頁
url = 'https://news.google.com/topstories?hl=zh-TW&gl=TW&ceid=TW:zh-Hant'
dom = requestHtml(url)

links = dom.xpath('//h3/a[@class="DY5T1d RZIKme"]/@href')
titles = dom.xpath('//h3/a[@class="DY5T1d RZIKme"]/text()')

print(links)
print(titles)

#限定搜尋結果(指定網站)
url = 'https://www.google.com/search?q=%E7%83%8F%E5%85%8B%E8%98%AD+site%3Altn.com.tw&oq=%E7%83%8F%E5%85%8B%E8%98%AD+site%3Altn.com.tw&aqs=chrome..69i57.9993j0j4&sourceid=chrome&ie=UTF-8'
dom = requestHtml(url)

links = dom.xpath('//h3/parent::a/@href')
titles = dom.xpath('//h3/text()')

print(links)
print(titles)

